#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'

const root = path.dirname(new URL(import.meta.url).pathname.replace(/^\/(.:)/, '$1'))
const model = JSON.parse(fs.readFileSync(path.join(root, 'traceability.json'), 'utf8'))
const write = (name, content) => fs.writeFileSync(path.join(root, name), `${content.trim()}\n`)
const index = new Map()
for (const key of ['promises', 'scenarios', 'capabilities', 'flows', 'informationArchitecture', 'navigation', 'views', 'uiElements', 'expectedBehaviors', 'exclusions', 'workPackages', 'runs', 'issues', 'decisions']) {
  for (const item of model[key] ?? []) index.set(item.id, item)
}
const refs = ids => ids.map(id => `\`${id}\``).join(', ')
const table = (headers, rows) => `| ${headers.join(' | ')} |\n|${headers.map(() => '---').join('|')}|\n${rows.map(row => `| ${row.map(value => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ')).join(' | ')} |`).join('\n')}`
const h = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')

write('customer-promise.md', `# UPD-001 Customer Promise\n\n**Update:** ${model.update.title} (${model.update.id})\n\n**Baseline:** ${model.update.baselineRevision} / ${model.update.baselineEvidenceRun}\n\n**Status:** ${model.update.status}\n\n**Target user:** ${model.stage.targetUser}\n\n**Objective quality gate:** ${model.stage.qualityGate}\n\n${model.promises.map(item => `## ${item.id} - ${item.statement}\n\n- **Host:** ${item.host}\n- **User:** ${item.user}\n- **Context:** ${item.context}\n- **Trigger:** ${item.trigger}\n- **Observable outcome:** ${item.outcome}\n- **Quality expectation:** ${item.quality}\n- **Recovery expectation:** ${item.recovery}\n- **Acceptance evidence:** ${item.evidence}\n- **Status:** ${item.status}`).join('\n\n')}\n\n## Governance\n\nThese promises layer above the immutable verified MVP baseline. They are specified, not implemented or verified. Any change begins as a new update or an explicit revision to UPD-001 before implementation evidence exists.`)

write('scenarios.md', `# UPD-001 User Scenarios\n\n${table(['ID', 'Host', 'Promises', 'Actor', 'Intent', 'Success'], model.scenarios.map(item => [item.id, item.host, refs(item.promiseIds), item.actor, item.intent, item.success]))}\n\n${model.scenarios.map(item => `## ${item.id}\n\n- **Host:** ${item.host}\n- **Promises:** ${refs(item.promiseIds)}\n- **Actor:** ${item.actor}\n- **Starting state:** ${item.startingState}\n- **Intent:** ${item.intent}\n- **Environment:** ${item.environment}\n- **Success:** ${item.success}\n- **Interruptions:** ${item.interruptions.join('; ')}\n- **Status:** ${item.status}`).join('\n\n')}`)

write('capabilities.md', `# UPD-001 User-Can Catalog\n\n${table(['ID', 'Host', 'User can statement', 'Scenarios', 'Status'], model.capabilities.map(item => [item.id, item.host, item.statement, refs(item.scenarioIds), item.status]))}`)

write('task-flows.md', `# UPD-001 Task Flows\n\nEvery flow is accepted only through visible interaction on its declared host. The verified MVP flows remain regression obligations.\n\n${model.flows.map(flow => `## ${flow.id}\n\n- **Host:** ${flow.host}\n- **Scenarios:** ${refs(flow.scenarioIds)}\n- **Capabilities:** ${refs(flow.capabilityIds)}\n- **Preconditions:** ${flow.preconditions.join('; ')}\n- **Completion:** ${flow.completion}\n- **Status:** ${flow.status}\n\n${table(['Step', 'User action', 'View', 'UI', 'Navigation', 'Objective behavior'], flow.steps.map(step => [step.id, step.action, `\`${step.viewId}\``, `\`${step.uiId}\``, step.navigationId ? `\`${step.navigationId}\`` : 'No route change', step.expectedBehaviorIds.map(id => `\`${id}\`: ${index.get(id).oracle}`).join('<br>')]))}`).join('\n\n')}`)

write('experience-architecture.md', `# UPD-001 Experience Architecture\n\n## Information Architecture\n\n${table(['ID', 'Object', 'Contains', 'Status'], model.informationArchitecture.map(item => [item.id, item.name, item.contains.join(', '), item.status]))}\n\n## Navigation\n\n${table(['ID', 'Label', 'Destination', 'Back behavior', 'Status'], model.navigation.map(item => [item.id, item.label, `\`${item.destination}\``, item.backBehavior, item.status]))}\n\n## Views\n\n${table(['ID', 'Name', 'Purpose', 'Information', 'Status'], model.views.map(item => [item.id, item.name, item.purpose, refs(item.informationIds), item.status]))}\n\n## UI Inventory\n\n${table(['ID', 'View', 'Role', 'Accessible name', 'Status'], model.uiElements.map(item => [item.id, `\`${item.viewId}\``, item.role, item.name, item.status]))}\n\n## Objective Expected Behaviors\n\n${table(['ID', 'Flow', 'Steps', 'Oracle', 'Status'], model.expectedBehaviors.map(item => [item.id, `\`${item.flowId}\``, refs(item.stepIds), item.oracle, item.status]))}`)

write('scope-ledger.md', `# UPD-001 Scope Ledger\n\n## Positive Scope\n\n${table(['Type', 'Count'], [['Customer promises', model.promises.length], ['Scenarios', model.scenarios.length], ['User-can capabilities', model.capabilities.length], ['Task flows', model.flows.length], ['Expected behaviors', model.expectedBehaviors.length]])}\n\n## Deliberate Exclusions\n\n${table(['ID', 'Expectation', 'Reason', 'Consequence', 'Disposition'], model.exclusions.map(item => [item.id, item.expectation, item.reason, item.consequence, item.disposition]))}\n\nAnything plausible for the dual-host promise but absent from both sections is a specification defect.`)

write('decisions.md', `# UPD-001 Decisions\n\n${model.decisions.map(item => `## ${item.id}\n\n- **Decision:** ${item.decision}\n- **Reversible:** ${item.reversible ? 'Yes' : 'No'}\n- **Evidence:** ${item.evidence}\n- **Status:** ${item.status}`).join('\n\n')}`)
write('execution-plan.md', `# UPD-001 Execution Plan\n\n${table(['ID', 'Depends on', 'Trace records', 'Gate', 'Status'], model.workPackages.map(item => [item.id, item.dependsOn.length ? refs(item.dependsOn) : 'None', refs(item.traceIds), item.gate, item.status]))}\n\nImplementation may begin only after UPD-001 is approved as a complete specified boundary. Packages advance by evidence, not completion estimates.`)

const docsPath = path.resolve(root, '..', '..', '..', 'docs', 'execution', 'updates', 'upd-001-dual-host-mvp.html')
fs.mkdirSync(path.dirname(docsPath), { recursive: true })
const hostCounts = Object.fromEntries(['web', 'desktop', 'cross-host', 'shared'].map(host => [host, model.flows.filter(flow => flow.host === host).length]))
const flowRows = model.flows.map(flow => `<tr><td><code>${h(flow.id)}</code></td><td>${h(flow.host)}</td><td>${h(flow.completion)}</td><td><span class="slate-badge">${h(flow.status)}</span></td></tr>`).join('\n')
const promiseCards = model.promises.map(item => `<article class="slate-card"><h3 class="slate-card__title"><code>${h(item.id)}</code></h3><p class="slate-card__body">${h(item.statement)}</p><p><span class="slate-badge">${h(item.host)}</span> <span class="slate-badge">${h(item.status)}</span></p></article>`).join('\n')
const packageRows = model.workPackages.map(item => `<tr><td><code>${h(item.id)}</code></td><td>${h(item.gate)}</td><td><span class="slate-badge">${h(item.status)}</span></td></tr>`).join('\n')
const exclusionRows = model.exclusions.map(item => `<tr><td><code>${h(item.id)}</code></td><td>${h(item.expectation)}</td><td>${h(item.disposition)}</td></tr>`).join('\n')
fs.writeFileSync(docsPath, `<!-- Generated from delivery/updates/UPD-001-dual-host-mvp/traceability.json. Do not edit manually. -->\n<header class="slate-hero"><p class="slate-hero__eyebrow">Product update · UPD-001</p><h1 class="slate-hero__title">Dual-Host Local-First MVP</h1><p class="slate-hero__summary">The formal promise-to-evidence specification for a GitHub Pages web workspace and portable Electron local-file workspace over one shared product core.</p></header>\n<aside class="slate-tldr"><p class="slate-tldr__label">TL;DR</p><p><strong>${model.promises.length} promises, ${model.scenarios.length} scenarios, ${model.capabilities.length} user-can statements, ${model.flows.length} task flows, and ${model.expectedBehaviors.length} objective behaviors</strong> define this update. Status: <strong>${h(model.update.status)}</strong>. The verified <code>f29c9f9</code> MVP remains the immutable baseline.</p></aside>\n<div class="slate-callout slate-callout--warning" role="note"><p class="slate-callout__title">Specified, not implemented</p><p>This page records the approved shape to review before implementation. No new flow inherits verification from the baseline. Status changes only from generated web, Electron, cross-host, migration, and regression evidence.</p></div>\n<h2>Customer promises</h2><div class="slate-card-grid" data-cols="2">${promiseCards}</div>\n<h2>Host coverage</h2><div class="slate-metrics"><div class="slate-metric"><p class="slate-metric__value">${hostCounts.web}</p><p class="slate-metric__label">Web flows</p></div><div class="slate-metric"><p class="slate-metric__value">${hostCounts.desktop}</p><p class="slate-metric__label">Desktop flows</p></div><div class="slate-metric"><p class="slate-metric__value">${hostCounts['cross-host']}</p><p class="slate-metric__label">Cross-host flows</p></div><div class="slate-metric"><p class="slate-metric__value">${model.exclusions.length}</p><p class="slate-metric__label">Deliberate exclusions</p></div></div>\n<h2>Task flows</h2><table><thead><tr><th>ID</th><th>Host</th><th>User completion</th><th>Status</th></tr></thead><tbody>${flowRows}</tbody></table>\n<h2>Execution packages</h2><table><thead><tr><th>ID</th><th>Evidence gate</th><th>Status</th></tr></thead><tbody>${packageRows}</tbody></table>\n<h2>Deliberate exclusions</h2><table><thead><tr><th>ID</th><th>Expectation</th><th>Disposition</th></tr></thead><tbody>${exclusionRows}</tbody></table>\n<h2>Review record</h2><p>The canonical update folder contains the request, immutable baseline, impact analysis, exhaustive generated specification, architecture decisions, release arithmetic, and future evidence. Follow the <a href="../../governance/product-update-pipeline.html">Product Update Pipeline</a> for every subsequent change.</p>\n`, 'utf8')

console.log(`Generated ${model.update.id}: ${index.size} records, ${model.flows.length} flows, ${model.exclusions.length} exclusions.`)
