#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'

const root = path.dirname(new URL(import.meta.url).pathname.replace(/^\/(.:)/, '$1'))
const model = JSON.parse(fs.readFileSync(path.join(root, 'traceability.json'), 'utf8'))
const index = new Map()
for (const key of ['promises','scenarios','capabilities','flows','informationArchitecture','navigation','views','uiElements','expectedBehaviors','exclusions','workPackages','runs','issues','decisions']) for (const item of model[key] ?? []) index.set(item.id, item)
const refs = ids => ids.map(id => `\`${id}\``).join(', ')
const table = (headers, rows) => `| ${headers.join(' | ')} |\n|${headers.map(() => '---').join('|')}|\n${rows.map(row => `| ${row.map(value => String(value).replaceAll('|','\\|').replaceAll('\n',' ')).join(' | ')} |`).join('\n')}`
const write = (name, content) => fs.writeFileSync(path.join(root, name), `${content.trim()}\n`)
const h = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')

write('customer-promise.md', `# UPD-003 Customer Promise\n\n**Update:** ${model.update.title} (${model.update.id})\n\n**Baseline:** ${model.update.baselineRevision} / ${model.update.baselineEvidenceRun}\n\n**Status:** ${model.update.status}\n\n**Target user:** ${model.stage.targetUser}\n\n**Objective quality gate:** ${model.stage.qualityGate}\n\n${model.promises.map(item => `## ${item.id} - ${item.statement}\n\n- **Host:** ${item.host}\n- **User:** ${item.user}\n- **Context:** ${item.context}\n- **Trigger:** ${item.trigger}\n- **Outcome:** ${item.outcome}\n- **Quality:** ${item.quality}\n- **Recovery:** ${item.recovery}\n- **Evidence:** ${item.evidence}\n- **Status:** ${item.status}`).join('\n\n')}`)
write('scenarios.md', `# UPD-003 Scenarios\n\n${table(['ID','Host','Promises','Actor','Intent','Success','Status'], model.scenarios.map(item => [item.id,item.host,refs(item.promiseIds),item.actor,item.intent,item.success,item.status]))}\n\n${model.scenarios.map(item => `## ${item.id}\n\n- **Starting state:** ${item.startingState}\n- **Environment:** ${item.environment}\n- **Interruptions:** ${item.interruptions.join('; ')}`).join('\n\n')}`)
write('capabilities.md', `# UPD-003 User-Can Catalog\n\n${table(['ID','Host','User can statement','Scenarios','Status'], model.capabilities.map(item => [item.id,item.host,item.statement,refs(item.scenarioIds),item.status]))}`)
write('task-flows.md', `# UPD-003 Task Flows\n\nEvery flow is accepted only through public UI on its declared host.\n\n${model.flows.map(flow => `## ${flow.id}\n\n- **Host:** ${flow.host}\n- **Scenarios:** ${refs(flow.scenarioIds)}\n- **Capabilities:** ${refs(flow.capabilityIds)}\n- **Preconditions:** ${flow.preconditions.join('; ')}\n- **Completion:** ${flow.completion}\n- **Status:** ${flow.status}\n\n${table(['Step','Action','View','UI','Navigation','Expected behavior'], flow.steps.map(step => [step.id,step.action,`\`${step.viewId}\``,`\`${step.uiId}\``,step.navigationId ? `\`${step.navigationId}\`` : 'No route change',step.expectedBehaviorIds.map(id => `\`${id}\`: ${index.get(id).oracle}`).join('<br>')]))}`).join('\n\n')}`)
write('experience-architecture.md', `# UPD-003 Experience Architecture\n\n## Information Architecture\n\n${table(['ID','Object','Contains','Status'], model.informationArchitecture.map(item => [item.id,item.name,item.contains.join(', '),item.status]))}\n\n## Navigation\n\n${table(['ID','Label','Destination','Back behavior','Status'], model.navigation.map(item => [item.id,item.label,`\`${item.destination}\``,item.backBehavior,item.status]))}\n\n## Views\n\n${table(['ID','Name','Purpose','Information','Status'], model.views.map(item => [item.id,item.name,item.purpose,refs(item.informationIds),item.status]))}\n\n## UI Inventory\n\n${table(['ID','View','Role','Accessible name','Status'], model.uiElements.map(item => [item.id,`\`${item.viewId}\``,item.role,item.name,item.status]))}\n\n## Expected Behaviors\n\n${table(['ID','Flow','Steps','Oracle','Status'], model.expectedBehaviors.map(item => [item.id,`\`${item.flowId}\``,refs(item.stepIds),item.oracle,item.status]))}`)

const docsPath = path.resolve(root, '..', '..', '..', 'docs', 'execution', 'updates', 'upd-003-terrain-environment-producer.html')
fs.mkdirSync(path.dirname(docsPath), { recursive: true })
const promiseCards = model.promises.map(item => `<article class="slate-card"><h3 class="slate-card__title"><code>${h(item.id)}</code></h3><p class="slate-card__body">${h(item.statement)}</p><p><span class="slate-badge">${h(item.host)}</span> <span class="slate-badge slate-badge--status">${h(item.status)}</span></p></article>`).join('\n')
const flowRows = model.flows.map(item => `<tr><td><code>${h(item.id)}</code></td><td>${h(item.host)}</td><td>${h(item.completion)}</td><td><span class="slate-badge slate-badge--status">${h(item.status)}</span></td></tr>`).join('\n')
const outRows = model.exclusions.map(item => `<tr><td><code>${h(item.id)}</code></td><td>${h(item.expectation)}</td><td>${h(item.disposition)}</td></tr>`).join('\n')
fs.writeFileSync(docsPath, `<!-- Generated from delivery/updates/UPD-003-terrain-environment-producer/traceability.json. Do not edit manually. -->\n<header class="slate-hero"><p class="slate-hero__eyebrow">Product update · UPD-003</p><h1 class="slate-hero__title">Terrain Environment Producer</h1><p class="slate-hero__summary">Add a deterministic 32px cardinal autotile producer to the same local-first project as the verified character workflow.</p></header>\n<aside class="slate-tldr"><p class="slate-tldr__label">TL;DR</p><p><strong>${model.promises.length} promises, ${model.scenarios.length} scenarios, ${model.capabilities.length} capabilities, ${model.flows.length} task flows, and ${model.expectedBehaviors.length} objective behaviors</strong> define this update. Status: <strong>${h(model.update.status)}</strong>.</p></aside>\n<div class="slate-callout slate-callout--tip" role="note"><p class="slate-callout__title">Approved · implementation authorized</p><p>The product owner requested the next bounded MVP scope, complete specification, documentation update, and implementation. Terrain is the roadmap's second producer; scenes, structures, packs, animation, and editor expansion remain excluded.</p></div>\n<h2>Customer promises</h2><div class="slate-card-grid" data-cols="2">${promiseCards}</div>\n<h2>Task flows</h2><table><thead><tr><th>ID</th><th>Host</th><th>Completion</th><th>Status</th></tr></thead><tbody>${flowRows}</tbody></table>\n<h2>Deliberate exclusions</h2><table><thead><tr><th>ID</th><th>Expectation</th><th>Disposition</th></tr></thead><tbody>${outRows}</tbody></table>\n<h2>Binding contracts</h2><p>See <code>product-design-spec.md</code>, <code>engineering-spec.md</code>, <code>quality-scenarios.md</code>, <code>threat-model.md</code>, and <code>release-gate.md</code> in the canonical update directory.</p>\n`, 'utf8')
console.log(`Generated UPD-003: ${index.size} records, ${model.flows.length} flows, ${model.exclusions.length} exclusions.`)
