import { strToU8, zipSync } from 'fflate'
import { creditsFor, exportBlockers } from './project'
import { buildAnimationManifest, pixelHash, renderSpritesheet } from './render'
import type { ContentPack, SpriteProject } from './types'

function canvasBytes(canvas: HTMLCanvasElement): Promise<Uint8Array> {
  return new Promise((resolve, reject) => canvas.toBlob(async blob => {
    if (!blob) return reject(new Error('Could not encode spritesheet PNG.'))
    resolve(new Uint8Array(await blob.arrayBuffer()))
  }, 'image/png'))
}

function creditsText(project: SpriteProject, pack?: ContentPack): string {
  const records = creditsFor(project, pack)
  return [
    `${project.name} - generated character credits`,
    '',
    ...records.flatMap(record => [
      `${record.source}`,
      `Author: ${record.author}`,
      `License: ${record.chosenLicense}`,
      `Source: ${record.sourceUrl}`,
      `Assets: ${record.assetNames.join(', ')}`,
      '',
    ]),
    'Generated by The Sprite Project. Preserve this file with distributed art.',
  ].join('\n')
}

function godotResource(): string {
  const manifest = buildAnimationManifest()
  const keys = Object.keys(manifest.animations)
  const subresources: string[] = []
  const animations: string[] = []
  let id = 1
  for (const key of keys) {
    const frames = manifest.animations[key]
    const frameRefs: string[] = []
    for (const frame of frames) {
      subresources.push(`[sub_resource type="AtlasTexture" id="AtlasTexture_${id}"]\natlas = ExtResource("1_texture")\nregion = Rect2(${frame.x}, ${frame.y}, ${frame.width}, ${frame.height})`)
      frameRefs.push(`{ "duration": ${frame.durationMs / 1000}, "texture": SubResource("AtlasTexture_${id}") }`)
      id += 1
    }
    animations.push(`{\n"frames": [${frameRefs.join(', ')}],\n"loop": true,\n"name": &"${key}",\n"speed": ${key.startsWith('walk') ? '5.55556' : '1.0'}\n}`)
  }
  return `[gd_resource type="SpriteFrames" load_steps=${id + 1} format=3]\n\n[ext_resource type="Texture2D" path="res://spritesheet.png" id="1_texture"]\n\n${subresources.join('\n\n')}\n\n[resource]\nanimations = [${animations.join(',\n')}]\n`
}

export async function buildPackage(project: SpriteProject, target: 'generic' | 'godot', pack?: ContentPack): Promise<{ bytes: Uint8Array; filename: string; renderHash: string }> {
  const blockers = exportBlockers(project, pack)
  if (blockers.length) throw new Error(blockers.join(' '))
  const sheet = renderSpritesheet(project, pack)
  const renderHash = pixelHash(sheet)
  const credits = creditsFor(project, pack)
  const manifest = buildAnimationManifest()
  const buildManifest = {
    schemaVersion: 1,
    projectId: project.id,
    projectName: project.name,
    packId: project.packId,
    packVersion: pack?.version ?? '1.0.0',
    packageSha256: pack?.packageSha256,
    characterId: project.character.id,
    renderHash,
    generatedBy: 'The Sprite Project MVP',
  }
  const files: Record<string, Uint8Array> = {
    'spritesheet.png': await canvasBytes(sheet),
    'animations.json': strToU8(JSON.stringify(manifest, null, 2)),
    'build-manifest.json': strToU8(JSON.stringify(buildManifest, null, 2)),
    'credits.json': strToU8(JSON.stringify({ schemaVersion: 1, records: credits }, null, 2)),
    'CREDITS.txt': strToU8(creditsText(project, pack)),
  }
  if (target === 'godot') {
    files['character_sprite_frames.tres'] = strToU8(godotResource())
    files['README-GODOT.md'] = strToU8(`# ${project.name} for Godot 4\n\nCopy the package contents into a Godot 4 project, load \`character_sprite_frames.tres\` into an \`AnimatedSprite2D\`, and select an animation such as \`walk_south\`. Frame regions and timing are already defined; no manual slicing is required.\n`)
  }
  const safeName = project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'character'
  return { bytes: zipSync(files, { level: 6 }), filename: `${safeName}-${target}.zip`, renderHash }
}

export function downloadBytes(bytes: Uint8Array, filename: string): void {
  const blob = new Blob([bytes as BlobPart], { type: 'application/zip' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  setTimeout(() => URL.revokeObjectURL(url), 0)
}
