import { strToU8, zipSync } from 'fflate'
import { canonicalJsonBytes } from './canonical'
import { parseProjectGraphV2 } from './schemas'
import { encodeRgbaPng } from './png'
import { renderTerrainAtlas, TERRAIN_MATERIALS, terrainPixelHash } from './terrain'
import type { ProjectGraphV2, TerrainDocumentV1 } from './types'

const FIXED_ZIP_TIME = new Date('1980-01-01T00:00:00.000Z')

function safeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'terrain'
}

function terrainManifest(document: TerrainDocumentV1, atlasHash: string) {
  return {
    schemaVersion: 1,
    tileWidth: 32,
    tileHeight: 32,
    columns: 4,
    rows: 4,
    materialId: document.materialId,
    atlasHash,
    masks: Array.from({ length: 16 }, (_, mask) => ({
      mask,
      north: Boolean(mask & 1),
      east: Boolean(mask & 2),
      south: Boolean(mask & 4),
      west: Boolean(mask & 8),
      x: (mask % 4) * 32,
      y: Math.floor(mask / 4) * 32,
      width: 32,
      height: 32,
    })),
  }
}

function godotTileSet(document: TerrainDocumentV1): string {
  const material = TERRAIN_MATERIALS[document.materialId]
  const tileLines: string[] = []
  for (let mask = 0; mask < 16; mask += 1) {
    const coordinate = `${mask % 4}:${Math.floor(mask / 4)}/0`
    tileLines.push(`${coordinate} = 0`, `${coordinate}/terrain_set = 0`, `${coordinate}/terrain = 0`)
    if (mask & 2) tileLines.push(`${coordinate}/terrains_peering_bit/right_side = 0`)
    if (mask & 4) tileLines.push(`${coordinate}/terrains_peering_bit/bottom_side = 0`)
    if (mask & 8) tileLines.push(`${coordinate}/terrains_peering_bit/left_side = 0`)
    if (mask & 1) tileLines.push(`${coordinate}/terrains_peering_bit/top_side = 0`)
  }
  const surface = Number.parseInt(document.palette.surface.slice(1), 16)
  const channel = (offset: number) => (((surface >> offset) & 255) / 255).toFixed(6).replace(/0+$/, '').replace(/\.$/, '')
  return `[gd_resource type="TileSet" load_steps=3 format=3]\n\n[ext_resource type="Texture2D" path="res://terrain-atlas.png" id="1_texture"]\n\n[sub_resource type="TileSetAtlasSource" id="TileSetAtlasSource_terrain"]\ntexture = ExtResource("1_texture")\ntexture_region_size = Vector2i(32, 32)\n${tileLines.join('\n')}\n\n[resource]\ntile_size = Vector2i(32, 32)\nterrain_set_0/mode = 2\nterrain_set_0/terrain_0/name = "${material.name}"\nterrain_set_0/terrain_0/color = Color(${channel(16)}, ${channel(8)}, ${channel(0)}, 1)\nsources/0 = SubResource("TileSetAtlasSource_terrain")\n`
}

function credits(document: TerrainDocumentV1) {
  const material = TERRAIN_MATERIALS[document.materialId]
  return {
    schemaVersion: 1,
    records: [{
      materialId: material.id,
      materialName: material.name,
      ...material.provenance,
    }],
  }
}

function creditsText(document: TerrainDocumentV1): string {
  const material = TERRAIN_MATERIALS[document.materialId]
  return `${document.name} - generated terrain credits\n\n${material.provenance.source}\nAuthor: ${material.provenance.author}\nLicense: ${material.provenance.chosenLicense}\nSource: ${material.provenance.sourceUrl}\n\nGenerated by The Sprite Project. Preserve this file with distributed art.\n`
}

export async function buildTerrainPackage(graphValue: ProjectGraphV2, target: 'generic' | 'godot'): Promise<{ bytes: Uint8Array; filename: string; renderHash: string }> {
  const graph = parseProjectGraphV2(graphValue)
  if (!graph.terrain) throw new Error('Create terrain before exporting it.')
  const document = graph.terrain
  const atlas = renderTerrainAtlas(document)
  const renderHash = terrainPixelHash(atlas)
  const files: Record<string, Uint8Array> = {
    'terrain-atlas.png': encodeRgbaPng(atlas),
    'terrain-manifest.json': canonicalJsonBytes(terrainManifest(document, renderHash)),
    'build-manifest.json': canonicalJsonBytes({
      schemaVersion: 1,
      projectId: graph.project.id,
      projectName: graph.project.name,
      terrainDocumentId: document.id,
      materialId: document.materialId,
      atlasHash: renderHash,
      generatedBy: 'The Sprite Project MVP',
    }),
    'credits.json': canonicalJsonBytes(credits(document)),
    'CREDITS.txt': strToU8(creditsText(document)),
  }
  if (target === 'godot') {
    files['terrain_tileset.tres'] = strToU8(godotTileSet(document))
    files['README-GODOT-TERRAIN.md'] = strToU8(`# ${document.name} for Godot 4.7.1\n\nCopy these files into a Godot project and assign \`terrain_tileset.tres\` to a \`TileMapLayer\`. The 16 cardinal terrain masks are already sliced and mapped; no peering-bit reconstruction is required.\n`)
  }
  const zipEntries = Object.fromEntries(Object.entries(files).map(([path, bytes]) => [path, [bytes, { level: 6 as const, mtime: FIXED_ZIP_TIME }]])) as Record<string, [Uint8Array, { level: 6; mtime: Date }]>
  return { bytes: zipSync(zipEntries), filename: `${safeName(graph.project.name)}-terrain-${target}.zip`, renderHash }
}