#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const root = path.dirname(new URL(import.meta.url).pathname.replace(/^\/(.:)/, "$1"));
const model = JSON.parse(fs.readFileSync(path.join(root, "traceability.json"), "utf8"));
const write = (name, content) => fs.writeFileSync(path.join(root, name), `${content.trim()}\n`);
const index = new Map();
for (const collection of [model.promises, model.scenarios, model.capabilities, model.flows, model.informationArchitecture, model.navigation, model.views, model.uiElements, model.expectedBehaviors, model.exclusions, model.workPackages, model.runs, model.issues, model.decisions]) {
  for (const item of collection) index.set(item.id, item);
}
const refs = ids => ids.map(id => `\`${id}\``).join(", ");
const table = (headers, rows) => `| ${headers.join(" | ")} |\n|${headers.map(() => "---").join("|")}|\n${rows.map(row => `| ${row.map(value => String(value).replaceAll("|", "\\|").replaceAll("\n", " ")).join(" | ")} |`).join("\n")}`;
const h = value => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const statusCounts = {};
for (const item of index.values()) statusCounts[item.status] = (statusCounts[item.status] ?? 0) + 1;

write("customer-promise.md", `# MVP Customer Promise\n\n**Stage:** ${model.stage.name}\n\n**Target user:** ${model.stage.targetUser}\n\n**Objective completion gate:** ${model.stage.qualityGate}\n\n${model.promises.map(p => `## ${p.id} - ${p.statement}\n\n- **User:** ${p.user}\n- **Context:** ${p.context}\n- **Trigger:** ${p.trigger}\n- **Observable outcome:** ${p.outcome}\n- **Quality expectation:** ${p.quality}\n- **Recovery expectation:** ${p.recovery}\n- **Acceptance evidence:** ${p.evidence}\n- **Status:** ${p.status}`).join("\n\n")}\n\n## Promise Boundary\n\nAnything plausible for the target user but not required by these five promises appears in [scope-ledger.md](scope-ledger.md). Absence from both the traceability model and exclusion ledger is a scope defect.`);

write("scenarios.md", `# MVP User Scenarios\n\n${table(["ID", "Promises", "Actor", "Intent", "Success"], model.scenarios.map(s => [s.id, refs(s.promiseIds), s.actor, s.intent, s.success]))}\n\n${model.scenarios.map(s => `## ${s.id}\n\n- **Promises:** ${refs(s.promiseIds)}\n- **Actor:** ${s.actor}\n- **Starting state:** ${s.startingState}\n- **Intent:** ${s.intent}\n- **Environment:** ${s.environment}\n- **Success:** ${s.success}\n- **Interruptions and branches:** ${s.interruptions.join("; ")}\n- **Status:** ${s.status}`).join("\n\n")}`);

write("capabilities.md", `# MVP User-Can Catalog\n\nThis is the complete positive capability scope. If a capability is absent, it is not silently implied. Plausible adjacent expectations are in [scope-ledger.md](scope-ledger.md).\n\n${table(["ID", "User can statement", "Scenarios", "Status"], model.capabilities.map(c => [c.id, c.statement, refs(c.scenarioIds), c.status]))}`);

write("task-flows.md", `# MVP Task Flows\n\nA task flow is accepted only through visible interaction in the production UI. Supporting code tests do not set flow status to verified.\n\n${model.flows.map(flow => `## ${flow.id}\n\n- **Scenarios:** ${refs(flow.scenarioIds)}\n- **Capabilities:** ${refs(flow.capabilityIds)}\n- **Preconditions:** ${flow.preconditions.join("; ")}\n- **Completion:** ${flow.completion}\n- **Status:** ${flow.status}\n\n${table(["Step", "User action", "View", "UI", "Navigation", "Expected behavior"], flow.steps.map(step => [step.id, step.action, `\`${step.viewId}\``, `\`${step.uiId}\``, step.navigationId ? `\`${step.navigationId}\`` : "No route change", step.expectedBehaviorIds.map(id => `\`${id}\`: ${index.get(id).oracle}`).join("<br>")]))}`).join("\n\n")}`);

write("experience-architecture.md", `# MVP Experience Architecture\n\n## Information Architecture\n\n${table(["ID", "Object", "Contains", "Status"], model.informationArchitecture.map(i => [i.id, i.name, i.contains.join(", "), i.status]))}\n\n## Navigation\n\n${table(["ID", "Label", "Destination", "Back behavior"], model.navigation.map(n => [n.id, n.label, `\`${n.destination}\``, n.backBehavior]))}\n\n## Views\n\n${table(["ID", "Name", "Purpose", "Information"], model.views.map(v => [v.id, v.name, v.purpose, refs(v.informationIds)]))}\n\n## UI Inventory\n\n${table(["ID", "View", "Role", "Accessible name", "Status"], model.uiElements.map(u => [u.id, `\`${u.viewId}\``, u.role, u.name, u.status]))}\n\n## Expected Behaviors\n\n${table(["ID", "Flow", "Steps", "Objective oracle", "Status"], model.expectedBehaviors.map(e => [e.id, `\`${e.flowId}\``, refs(e.stepIds), e.oracle, e.status]))}`);

write("scope-ledger.md", `# MVP Scope Ledger\n\n## Included\n\n${table(["Type", "Count", "Canonical source"], [["Customer promises", model.promises.length, "traceability.json / customer-promise.md"], ["Scenarios", model.scenarios.length, "traceability.json / scenarios.md"], ["User-can capabilities", model.capabilities.length, "traceability.json / capabilities.md"], ["Task flows", model.flows.length, "traceability.json / task-flows.md"], ["Expected behaviors", model.expectedBehaviors.length, "traceability.json / experience-architecture.md"]])}\n\n## Deliberately Excluded\n\n${table(["ID", "Expectation", "Reason", "Consequence", "Disposition"], model.exclusions.map(o => [o.id, o.expectation, o.reason, o.consequence, o.disposition]))}\n\nAn item absent from both sections is an omission to fix, not an implicit exclusion.`);

write("execution-plan.md", `# MVP Execution Plan\n\n${table(["ID", "Depends on", "Trace records", "Gate", "Status"], model.workPackages.map(w => [w.id, w.dependsOn.length ? refs(w.dependsOn) : "None", refs(w.traceIds), w.gate, w.status]))}\n\n## Autonomous Defaults\n\n- Continue through every unblocked package.\n- Prefer reversible local choices.\n- Produce evidence before changing a record to verified.\n- Block only the affected legal, credential, independent-user, or publishing gate.\n- Do not publish, deploy, or infer legal approval while the owner is unavailable.`);

write("decisions.md", `# MVP Decisions\n\n${model.decisions.map(d => `## ${d.id}\n\n- **Decision:** ${d.decision}\n- **Reversible:** ${d.reversible ? "Yes" : "No"}\n- **Evidence:** ${d.evidence}\n- **Status:** ${d.status}`).join("\n\n")}`);
write("issues.md", `# MVP Issues\n\n${model.issues.length ? table(["ID", "Severity", "Affected", "Disposition", "Status"], model.issues.map(i => [i.id, i.severity, refs(i.traceIds), i.disposition, i.status])) : "No observed implementation or actual-UI anomalies are recorded yet. An empty list before implementation is not evidence of quality."}`);

fs.mkdirSync(path.join(root, "evidence", "runs"), { recursive: true });
write(path.join("evidence", "README.md"), `# MVP Evidence\n\nActual-UI runs are stored under \`runs/<RUN-ID>/\`. Each run records the commit, production build, browser environment, raw screenshots and captures, downloads, console/page/network events, expectation outcomes, and anomalies.\n\n## Acceptance\n\nThe MVP requires every \`TF-*\` and \`EB-*\` to have a passing latest run and no unresolved severity 0-2 issue. Unit and integration checks remain supporting evidence only.`);

const docsPath = path.resolve(root, "..", "..", "docs", "execution", "mvp-delivery.html");
const flowRows = model.flows.map(f => `<tr><td><code>${h(f.id)}</code></td><td>${h(f.completion)}</td><td><span class="slate-badge">${h(f.status)}</span></td></tr>`).join("\n");
const promiseCards = model.promises.map(p => `<article class="slate-card"><h3 class="slate-card__title"><code>${h(p.id)}</code></h3><p class="slate-card__body">${h(p.statement)}</p><p><span class="slate-badge">${h(p.status)}</span></p></article>`).join("\n");
const exclusionRows = model.exclusions.map(o => `<tr><td><code>${h(o.id)}</code></td><td>${h(o.expectation)}</td><td>${h(o.reason)}</td><td>${h(o.disposition)}</td></tr>`).join("\n");
const count = key => model[key]?.length ?? 0;
fs.writeFileSync(docsPath, `<!-- Generated from delivery/mvp/traceability.json. Do not edit manually. -->\n<header class="slate-hero"><p class="slate-hero__eyebrow">Execution · MVP control plane</p><h1 class="slate-hero__title">MVP Delivery Tracker</h1><p class="slate-hero__summary">The inspectable promise-to-evidence record for the complete character-to-Godot MVP.</p></header>\n<aside class="slate-tldr"><p class="slate-tldr__label">TL;DR</p><p><strong>${count("promises")} promises, ${count("scenarios")} scenarios, ${count("capabilities")} user capabilities, ${count("flows")} task flows, and ${count("expectedBehaviors")} objective behaviors</strong> define the positive scope. ${count("exclusions")} plausible adjacent expectations are deliberately excluded. Current stage: <strong>${h(model.stage.status)}</strong>.</p></aside>\n<div class="slate-callout slate-callout--info" role="note"><p class="slate-callout__title">Canonical source</p><p>This page is generated from <code>delivery/mvp/traceability.json</code>. Status becomes verified only from actual-UI run evidence.</p></div>\n<h2>Customer promises</h2><div class="slate-card-grid" data-cols="2">${promiseCards}</div>\n<h2>Objective scope counts</h2><div class="slate-metrics"><div class="slate-metric"><p class="slate-metric__value">${count("capabilities")}</p><p class="slate-metric__label">User-can statements</p></div><div class="slate-metric"><p class="slate-metric__value">${count("flows")}</p><p class="slate-metric__label">Actual task flows</p></div><div class="slate-metric"><p class="slate-metric__value">${count("expectedBehaviors")}</p><p class="slate-metric__label">Behavior oracles</p></div><div class="slate-metric"><p class="slate-metric__value">${count("issues")}</p><p class="slate-metric__label">Observed anomalies</p></div></div>\n<h2>Task-flow status</h2><table><thead><tr><th>ID</th><th>User completion</th><th>Status</th></tr></thead><tbody>${flowRows}</tbody></table>\n<h2>Deliberate exclusions</h2><table><thead><tr><th>ID</th><th>Expectation</th><th>Reason</th><th>Disposition</th></tr></thead><tbody>${exclusionRows}</tbody></table>\n<h2>Review the complete record</h2><p>The repository delivery folder contains the exhaustive <code>customer-promise.md</code>, <code>scenarios.md</code>, <code>capabilities.md</code>, <code>task-flows.md</code>, <code>experience-architecture.md</code>, <code>scope-ledger.md</code>, decisions, issues, execution plan, and evidence runs.</p>\n`, "utf8");

console.log(`Generated MVP documentation: ${index.size} records, ${model.flows.length} flows, ${model.exclusions.length} exclusions.`);
