export const CHANNELS = {
  getHostInfo: 'host:get-info',
  listRecentProjects: 'recent:list',
  openRecentProject: 'recent:open',
  forgetRecentProject: 'recent:forget',
  chooseProjectFolder: 'dialog:project-folder',
  chooseProjectFile: 'dialog:project-file',
  chooseExportDirectory: 'dialog:export-directory',
  readProject: 'project:read',
  saveProject: 'project:save',
  inspectArchive: 'archive:inspect',
  writeArchive: 'archive:write',
  writeExport: 'export:write',
  choosePackFile: 'dialog:pack-file',
  readPack: 'pack:read',
  listInstalledPacks: 'pack:list',
  installPack: 'pack:install',
  removePack: 'pack:remove',
  writePack: 'pack:write',
} as const